-- ============================================================
-- Multi-source food schema for Supabase
-- Matches multisource_food_schema.mermaid:
--   FDC (Foundation, SR Legacy, FNDDS Survey) + BLS 4.0 + INDB,
--   images, aliases, tags, i18n.
-- Run with: supabase db push / psql "$SUPABASE_DB_URL" -f schema.sql
--
-- Load order for the generated CSVs (fdc_to_ont_csv.py,
-- bls_to_ont_csv.py, indb_to_ont_csv.py):
--   food_source, nutrient, nutrient_mapping, food_category, food,
--   food_nutrient, measure_unit, food_portion, market_acquisition,
--   input_food, food_component, retention_factor, food_image,
--   food_alias
-- then: REFRESH MATERIALIZED VIEW food_summary;
-- ============================================================

-- ---------- 1. Source registry ------------------------------

create table if not exists food_source (
    code          text primary key,          -- fdc_foundation | fdc_sr_legacy | bls
    name          text not null,
    license_note  text
);

-- ---------- 2. Canonical core -------------------------------

create table if not exists food_category (
    id           int  primary key,
    source       text references food_source (code),  -- null = canonical
    description  text not null
);

create table if not exists food (
    id                bigint primary key,
    source            text   not null references food_source (code),
    source_code       text   not null,               -- fdc_id | BLS code
    description       text   not null,               -- full English name
    short_title       text,                          -- concise display name
    food_category_id  int    references food_category (id),
    publication_date  date,
    unique (source, source_code)
);

create table if not exists nutrient (
    id         int     primary key,   -- canonical app nutrient list
    name       text    not null,
    unit_name  text    not null,      -- G | MG | UG | KCAL
    rank       numeric
);

-- Import-time mapping: source component code -> canonical nutrient.
-- `source` is the import FAMILY (fdc | bls | indb), NOT a
-- food_source.code: 'fdc' covers fdc_foundation / fdc_sr_legacy /
-- fdc_survey, so there is deliberately no FK here.
-- No FK on source_component_code either: it references FDC nutrient
-- ids, BLS component codes, INDB column names depending on source.
create table if not exists nutrient_mapping (
    source                 text    not null,
    source_component_code  text    not null,
    nutrient_id            int     not null references nutrient (id),
    unit_factor            numeric not null default 1,
    primary key (source, source_component_code)
);

create table if not exists food_nutrient (
    id           bigint  primary key,
    food_id      bigint  not null references food (id) on delete cascade,
    nutrient_id  int     not null references nutrient (id),
    amount       numeric not null,    -- per 100 g, canonical unit
    origin       text,                -- analysis | calculated | label | literature
    reference    text,
    data_points  int,
    min          numeric,
    max          numeric,
    unique (food_id, nutrient_id)
);

create table if not exists measure_unit (
    id    int  primary key,
    name  text not null
);

create table if not exists food_portion (
    id                   bigint  primary key,
    food_id              bigint  not null references food (id) on delete cascade,
    amount               numeric,
    measure_unit_id      int     not null references measure_unit (id),
    portion_description  text,
    modifier             text,
    seq_num              int,
    gram_weight          numeric not null
);

create table if not exists food_image (
    id            bigint generated by default as identity primary key,
    food_id       bigint not null references food (id) on delete cascade,
    kind          text   not null check (kind in ('thumbnail', 'main')),
    storage_path  text,               -- key in the 'food-images' bucket
    external_url  text,
    width         int,
    height        int,
    attribution   text,
    -- true when the image was AI-generated (DALL-E, Imagen...). Keep
    -- accurate: generated food photos can mislead users about what a
    -- product looks like, and disclosure rules may require labeling.
    ai_generated  boolean not null default false,
    created_at    timestamptz not null default now(),
    check (num_nonnulls(storage_path, external_url) = 1)
);

-- ---------- 2b. Search: aliases & tags ------------------------

create table if not exists food_alias (
    id          bigint generated by default as identity primary key,
    food_id     bigint not null references food (id) on delete cascade,
    locale      text   not null,     -- BCP 47: de, hi-Latn...
    alias       text   not null,     -- Spaghetti, Garam Chai...
    source      text   not null default 'curated'
                check (source in ('curated', 'community', 'derived')),
    created_at  timestamptz not null default now(),
    unique (food_id, locale, alias)
);

create table if not exists tag (
    id    int generated by default as identity primary key,
    slug  text not null unique,      -- vegan, breakfast, high-protein...
    kind  text                       -- diet | allergen | meal_type | custom
);

create table if not exists food_tag (
    food_id  bigint not null references food (id) on delete cascade,
    tag_id   int    not null references tag (id) on delete cascade,
    source   text,                   -- curated | derived | community
    primary key (food_id, tag_id)
);

create table if not exists tag_translation (
    tag_id  int  not null references tag (id) on delete cascade,
    locale  text not null,
    name    text not null,           -- vegan -> Vegan, high-protein -> Proteinreich
    primary key (tag_id, locale)
);

-- ---------- 3. Localization ---------------------------------

create table if not exists food_translation (
    food_id       bigint not null references food (id) on delete cascade,
    locale        text   not null,    -- BCP 47: de, fr, es...
    description   text   not null,
    source        text   not null default 'machine'
                  check (source in ('native', 'machine', 'community', 'verified')),
    -- true when produced by MT/LLM (DeepL, GPT...). Stays true after a
    -- human review upgrades source to 'verified', preserving provenance;
    -- may also matter for EU AI Act style disclosure duties.
    ai_generated  boolean not null default false,
    updated_at    timestamptz not null default now(),
    primary key (food_id, locale)
);

create table if not exists food_category_translation (
    food_category_id  int  not null references food_category (id) on delete cascade,
    locale            text not null,
    description       text not null,
    primary key (food_category_id, locale)
);

create table if not exists food_portion_translation (
    food_portion_id  bigint not null references food_portion (id) on delete cascade,
    locale           text   not null,
    portion_description  text,
    modifier             text,
    -- Same provenance vocabulary as food_translation. Seeded machine output
    -- is not fit to show: the app displays only 'verified' rows and falls
    -- back to its own word for "serving" otherwise.
    source        text not null default 'machine'
                  check (source in ('native', 'machine', 'community', 'verified')),
    ai_generated  boolean not null default false,
    updated_at    timestamptz not null default now(),
    primary key (food_portion_id, locale)
);

create table if not exists measure_unit_translation (
    measure_unit_id  int  not null references measure_unit (id) on delete cascade,
    locale           text not null,
    name             text not null,
    -- Same provenance vocabulary as food_translation. Seeded machine output
    -- is not fit to show: the app is expected to display only 'verified'
    -- rows and fall back to its own word for "serving" otherwise.
    source        text not null default 'machine'
                  check (source in ('native', 'machine', 'community', 'verified')),
    ai_generated  boolean not null default false,
    updated_at    timestamptz not null default now(),
    primary key (measure_unit_id, locale)
);

-- ---------- 4. Source-specific side tables ------------------

create table if not exists bls_component (
    code             text primary key,   -- ENERCC, WATER, PROT625...
    name_de          text not null,
    name_en          text not null,
    unit             text not null,
    component_group  text,
    formula          text
);

create table if not exists market_acquisition (
    food_id            bigint primary key references food (id) on delete cascade,
    upc_code           text,
    brand_description  text
);

create table if not exists input_food (
    id             bigint  primary key,
    food_id        bigint  not null references food (id) on delete cascade,
    input_food_id  bigint  references food (id),
    gram_weight    numeric
);

create table if not exists food_component (
    id          bigint  primary key,
    food_id     bigint  not null references food (id) on delete cascade,
    name        text    not null,
    pct_weight  numeric,
    is_refuse   boolean not null
);

create table if not exists retention_factor (
    id           int  primary key,
    code         text not null,
    description  text not null
);

-- ---------- 5. Indexes --------------------------------------

create index if not exists idx_food_nutrient_food     on food_nutrient (food_id);
create index if not exists idx_food_portion_food      on food_portion (food_id, seq_num);
create index if not exists idx_food_image_food        on food_image (food_id, kind);
create index if not exists idx_food_translation_loc   on food_translation (locale);
create index if not exists idx_food_category_food     on food (food_category_id);

-- Full-text search: English on food, per-locale on translations.
create index if not exists idx_food_description_fts
    on food using gin (to_tsvector('english', description));
create index if not exists idx_food_translation_fts
    on food_translation using gin (to_tsvector('simple', description));
-- Fuzzy search (ILIKE '%term%') support:
create extension if not exists pg_trgm;
create index if not exists idx_food_description_trgm
    on food using gin (description gin_trgm_ops);
create index if not exists idx_food_translation_trgm
    on food_translation using gin (description gin_trgm_ops);
create index if not exists idx_food_alias_trgm
    on food_alias using gin (alias gin_trgm_ops);
create index if not exists idx_food_alias_locale on food_alias (locale, alias);
create index if not exists idx_food_tag_tag on food_tag (tag_id);

-- ---------- 6. App-facing materialized view -----------------
-- The Flutter app queries ONLY this view (+ food_translation for i18n).
-- Nutrient pivot follows MealNutrimentsDBO; canonical nutrient ids are
-- fixed by fdc_to_ont_csv.py (1=energy ... 24=niacin).

-- True when portions_by_food_ids (6b) would return at least one row for the
-- food: the same predicate, kept in one place so the two cannot drift.
-- Defined ahead of the view because the view stores it as has_portion
-- (migrations 2026-09-12_search_rpc_order_by_portions.sql and
-- 2026-09-13_food_summary_has_portion.sql).
create or replace function food_has_deliverable_portion(fid bigint)
returns boolean
language sql
stable
security invoker
set search_path = public, pg_temp
as $$
    select exists (
        select 1
        from food_portion fp
        where fp.food_id = fid
          and fp.portion_description is not null
          and fp.portion_description <> 'Quantity not specified'
          and fp.gram_weight is not null
          and fp.gram_weight > 0
          and fp.portion_description !~* '\mNFS\M|\mNS as to\M|\myields\M|^Guideline amount'
    )
$$;

create materialized view if not exists food_summary as
select
    f.id                                   as food_id,
    f.source,
    f.source_code,
    f.description                          as name,
    coalesce(f.short_title, f.description) as short_title,  -- concise label
    ma.brand_description                   as brands,      -- MealDBO.brands
    ma.upc_code                            as barcode,     -- scanned lookup
    fc.description                         as category,
    p.amount                               as serving_quantity,
    -- FDC's measure_unit 9999 is literally named 'undetermined' (a portion
    -- with no household measure). Present it as 'portion' — the label the
    -- app used to map id 9999 to — instead of leaking the raw name.
    case when mu.name = 'undetermined' then 'portion' else mu.name end
                                           as serving_unit,
    -- Household measure of the default portion. FDC splits it across two
    -- columns: FNDDS writes prose into portion_description, while SR
    -- Legacy/Foundation leave that empty and put the measure text ("slice",
    -- "cup, sliced") into modifier — their measure_unit is 'undetermined'
    -- precisely because the real unit lives there. Fall back to
    -- "<amount> <modifier>" so those foods get "1 slice" instead of nothing.
    coalesce(
        nullif(p.portion_description, ''),
        case when nullif(p.modifier, '') is not null
             then trim(concat_ws(' ', p.amount::text, p.modifier))
        end
    )                                      as serving_size,
    p.gram_weight                          as serving_gram_weight,
    coalesce(it.external_url, '/storage/v1/object/public/food-images/' || it.storage_path)
                                           as thumbnail_url,
    coalesce(im.external_url, '/storage/v1/object/public/food-images/' || im.storage_path)
                                           as main_image_url,
    tg.tags,
    n.energy_kcal_100,
    n.carbohydrates_100,
    n.fat_100,
    n.proteins_100,
    n.sugars_100,
    n.saturated_fat_100,
    n.fiber_100,
    n.monounsaturated_fat_100,
    n.polyunsaturated_fat_100,
    n.trans_fat_100,
    n.cholesterol_100,
    n.sodium_100,
    n.potassium_100,
    n.magnesium_100,
    n.calcium_100,
    n.iron_100,
    n.zinc_100,
    n.phosphorus_100,
    n.vitamin_a_100,
    n.vitamin_c_100,
    n.vitamin_d_100,
    n.vitamin_b6_100,
    n.vitamin_b12_100,
    n.niacin_100,
    -- True when portions_by_food_ids would return at least one row for this
    -- food — the same helper the search order has used since 2026-09-12, now
    -- stored so the app's cut can read it (#1190). Never NULL: it is an
    -- EXISTS. Recomputed on every refresh.
    food_has_deliverable_portion(f.id)     as has_portion
from food f
left join food_category fc on fc.id = f.food_category_id
left join market_acquisition ma on ma.food_id = f.id   -- brand + barcode
left join lateral (                      -- first portion = default serving
    select fp.amount, fp.portion_description, fp.modifier, fp.gram_weight,
           fp.measure_unit_id
    from food_portion fp
    where fp.food_id = f.id
    order by fp.seq_num nulls last, fp.id
    limit 1
) p on true
left join measure_unit mu on mu.id = p.measure_unit_id
left join lateral (
    select fi.external_url, fi.storage_path from food_image fi
    where fi.food_id = f.id and fi.kind = 'thumbnail'
    order by fi.id limit 1
) it on true
left join lateral (
    select fi.external_url, fi.storage_path from food_image fi
    where fi.food_id = f.id and fi.kind = 'main'
    order by fi.id limit 1
) im on true
left join lateral (
    select array_agg(t.slug order by t.slug) as tags
    from food_tag ft2
    join tag t on t.id = ft2.tag_id
    where ft2.food_id = f.id
) tg on true
left join lateral (
    select
        max(fn.amount) filter (where fn.nutrient_id = 1)  as energy_kcal_100,
        max(fn.amount) filter (where fn.nutrient_id = 2)  as carbohydrates_100,
        max(fn.amount) filter (where fn.nutrient_id = 3)  as fat_100,
        max(fn.amount) filter (where fn.nutrient_id = 4)  as proteins_100,
        max(fn.amount) filter (where fn.nutrient_id = 5)  as sugars_100,
        max(fn.amount) filter (where fn.nutrient_id = 6)  as saturated_fat_100,
        max(fn.amount) filter (where fn.nutrient_id = 7)  as fiber_100,
        max(fn.amount) filter (where fn.nutrient_id = 8)  as monounsaturated_fat_100,
        max(fn.amount) filter (where fn.nutrient_id = 9)  as polyunsaturated_fat_100,
        max(fn.amount) filter (where fn.nutrient_id = 10) as trans_fat_100,
        max(fn.amount) filter (where fn.nutrient_id = 11) as cholesterol_100,
        max(fn.amount) filter (where fn.nutrient_id = 12) as sodium_100,
        max(fn.amount) filter (where fn.nutrient_id = 13) as potassium_100,
        max(fn.amount) filter (where fn.nutrient_id = 14) as magnesium_100,
        max(fn.amount) filter (where fn.nutrient_id = 15) as calcium_100,
        max(fn.amount) filter (where fn.nutrient_id = 16) as iron_100,
        max(fn.amount) filter (where fn.nutrient_id = 17) as zinc_100,
        max(fn.amount) filter (where fn.nutrient_id = 18) as phosphorus_100,
        max(fn.amount) filter (where fn.nutrient_id = 19) as vitamin_a_100,
        max(fn.amount) filter (where fn.nutrient_id = 20) as vitamin_c_100,
        max(fn.amount) filter (where fn.nutrient_id = 21) as vitamin_d_100,
        max(fn.amount) filter (where fn.nutrient_id = 22) as vitamin_b6_100,
        max(fn.amount) filter (where fn.nutrient_id = 23) as vitamin_b12_100,
        max(fn.amount) filter (where fn.nutrient_id = 24) as niacin_100
    from food_nutrient fn
    where fn.food_id = f.id
) n on true;

-- Required for REFRESH MATERIALIZED VIEW CONCURRENTLY:
create unique index if not exists idx_food_summary_id on food_summary (food_id);
create index if not exists idx_food_summary_source on food_summary (source);
create index if not exists idx_food_summary_name_trgm
    on food_summary using gin (name gin_trgm_ops);
create index if not exists idx_food_summary_tags
    on food_summary using gin (tags);   -- WHERE tags @> array['vegan']
create index if not exists idx_food_summary_barcode   -- barcode scan lookup (branded/OFF)
    on food_summary (barcode) where barcode is not null;

-- Supports search_food_summary below. The app's previous PostgREST
-- `textSearch` on this column had no index at all, so English search was a
-- sequential scan of the whole view; the RPC is only as fast as what backs
-- it, and this is what backs it.
create index if not exists idx_food_summary_name_fts
    on food_summary using gin (to_tsvector('english', name));

-- ---------- 6b. App-facing search functions -----------------
-- The app calls these instead of filtering the view over the URL, so a
-- search term never reaches the API gateway log.
--
-- PostgREST turns a table query into a GET, which puts the term in the
-- query string; it issues an RPC as a POST with a JSON body. The gateway
-- log records `request.url` and `request.search` but has no body field, and
-- those URLs sit in the same record as the caller's IP, city, postal code,
-- ISP and TLS fingerprint. Removing that pairing is the whole point.
-- App issue simonoppowa/OpenNutriTracker#882.
--
-- Ranking stays in the app; what these decide is which hundred rows reach
-- it. Since 2026-09-12_search_rpc_order_by_portions.sql and
-- 2026-09-13_search_rpc_order_title_first.sql the pool is ordered: records
-- with a deliverable portion first (has_portion, stored on the view since
-- 2026-09-13_food_summary_has_portion.sql), then the records whose title —
-- the text before the first comma — is the term, then the shortest
-- description, then food_id. Without it a large family never reached the
-- app at all ("Potato, NFS" was rank 128 of 712 matches for potato). No
-- `ts_rank`: relevance among the hundred is the app's.

create or replace function search_food_summary(
    term      text,
    sources   text[] default null,
    max_rows  int    default 100
)
returns setof food_summary
language sql
stable
security invoker
set search_path = public, pg_temp
as $$
    select fs.*
    from food_summary fs
    where to_tsvector('english', fs.name)
          @@ websearch_to_tsquery('english', term)
      and (sources is null or fs.source = any (sources))
    order by fs.has_portion desc,
             (lower(btrim(split_part(fs.name, ',', 1))) = lower(btrim(term))) desc,
             length(fs.name),
             fs.food_id
    limit greatest(max_rows, 0)
$$;

-- has_portion is the view's stored flag by a left join (coalesced to false;
-- every food_translation row has a summary row, and the FK to food keeps it
-- so), so the two hops of a localized search cannot disagree on it. A
-- database that still has the 39-column view and the three-column version
-- of this function needs 2026-09-13_food_summary_has_portion.sql, which
-- recreates both: CREATE OR REPLACE cannot change a return type, and IF NOT
-- EXISTS leaves the view as it is.
create or replace function search_food_translation(
    term      text,
    loc       text,
    max_rows  int default 100
)
returns table (food_id bigint, description text, source text, has_portion boolean)
language sql
stable
security invoker
set search_path = public, pg_temp
as $$
    select ft.food_id, ft.description, ft.source,
           coalesce(fs.has_portion, false) as has_portion
    from food_translation ft
    left join food_summary fs on fs.food_id = ft.food_id
    where ft.locale = loc
      and to_tsvector('simple', ft.description)
          @@ websearch_to_tsquery('simple', term)
    order by coalesce(fs.has_portion, false) desc,
             (lower(btrim(split_part(ft.description, ',', 1))) = lower(btrim(term))) desc,
             length(ft.description),
             ft.food_id
    limit greatest(max_rows, 0)
$$;

-- The localized path needs a second hop: the app ranks the translation
-- matches itself and then fetches the summary rows for the ids that
-- survived. Those ids are derived from the term, so sending them as a
-- filter would put a fingerprint of the search back in the URL — which is
-- why this is an RPC too rather than a plain `in.(...)` query.
create or replace function food_summary_by_ids(
    ids      bigint[],
    sources  text[] default null
)
returns setof food_summary
language sql
stable
security invoker
set search_path = public, pg_temp
as $$
    select fs.*
    from food_summary fs
    where fs.food_id = any (ids)
      and (sources is null or fs.source = any (sources))
$$;

-- ---------- 7. Row Level Security ---------------------------
-- Reference data: readable by everyone, writable only by service_role
-- (service_role bypasses RLS; no insert/update policies needed).

do $$
declare t text;
begin
    foreach t in array array[
        'food_source', 'food_category', 'food', 'nutrient',
        'nutrient_mapping', 'food_nutrient', 'measure_unit',
        'food_portion', 'food_image', 'food_translation',
        'food_category_translation', 'food_portion_translation',
        'measure_unit_translation', 'bls_component',
        'market_acquisition', 'input_food', 'food_component',
        'retention_factor', 'food_alias', 'tag', 'food_tag',
        'tag_translation'
    ] loop
        execute format('alter table %I enable row level security', t);
        execute format('drop policy if exists "public read" on %I', t);
        execute format(
            'create policy "public read" on %I for select to anon, authenticated using (true)', t);
    end loop;
end $$;

-- Materialized views have no RLS; restrict via grants instead.
revoke all on food_summary from anon, authenticated;
grant select on food_summary to anon, authenticated;

-- Functions are executable by PUBLIC on creation, so the grant is only
-- meaningful after the revoke.
-- A food's default portion label in the reader's language, and only when a
-- human has verified it. A function rather than a table read for the reason
-- the search functions are: a GET puts the food id in the gateway log beside
-- the caller's IP. The lateral pick mirrors food_summary's, so the label
-- describes the same portion its serving_gram_weight came from.
create or replace function portion_labels_by_food_ids(
    ids  bigint[],
    loc  text
)
returns table (food_id bigint, label text)
language sql
stable
as $$
    select f.id, t.portion_description
    from unnest(ids) as f(id)
    join lateral (
        select fp.id
        from food_portion fp
        where fp.food_id = f.id
        order by fp.seq_num nulls last, fp.id
        limit 1
    ) p on true
    join food_portion_translation t
      on t.food_portion_id = p.id
     and t.locale = loc
     and t.source = 'verified'
    where t.portion_description is not null
      and btrim(t.portion_description) <> '';
$$;

revoke execute on function search_food_summary(text, text[], int) from public;
revoke execute on function search_food_translation(text, text, int) from public;
revoke execute on function food_summary_by_ids(bigint[], text[]) from public;
grant execute on function search_food_summary(text, text[], int)
    to anon, authenticated;
grant execute on function search_food_translation(text, text, int)
    to anon, authenticated;
grant execute on function food_summary_by_ids(bigint[], text[])
    to anon, authenticated;
-- The helper is called at the view's refresh and, until 2026-09-13, from
-- inside the two search functions; it is not an API of its own.
revoke execute on function food_has_deliverable_portion(bigint) from public;
grant execute on function food_has_deliverable_portion(bigint)
    to anon, authenticated;
-- Every usable portion a food has, so the app can offer a choice rather than
-- the single one food_summary picks. Ordered like that lateral pick, so row 1
-- is the default the app already uses. `localized` says whether `label` came
-- from a verified translation or is the English text, because the two are
-- indistinguishable as strings. `label_en` is always the English text, so a
-- portion word the AI model was told to emit in English has something to
-- match in every locale; it equals `label` exactly when `localized` is false.
--
-- This file bootstraps an empty database. On one that already holds the
-- five-column version of this function, `create or replace` fails with
-- "cannot change return type of existing function": run
-- 2026-09-13_portions_by_food_ids_label_en.sql instead, which drops and
-- recreates it in one transaction — the same rule search_food_translation
-- carries above for 2026-09-13_food_summary_has_portion.sql.
create or replace function portions_by_food_ids(
    ids  bigint[],
    loc  text
)
returns table (
    food_id      bigint,
    seq          int,
    label        text,
    localized    boolean,
    gram_weight  numeric,
    label_en     text
)
language sql
stable
as $$
    select
        fp.food_id,
        row_number() over (
            partition by fp.food_id
            order by fp.seq_num nulls last, fp.id
        )::int,
        coalesce(t.portion_description, fp.portion_description),
        t.portion_description is not null,
        fp.gram_weight,
        fp.portion_description
    from food_portion fp
    join unnest(ids) as w(id) on w.id = fp.food_id
    left join food_portion_translation t
           on t.food_portion_id = fp.id
          and t.locale = loc
          and t.source = 'verified'
          and t.portion_description is not null
          and btrim(t.portion_description) <> ''
    where fp.portion_description is not null
      and fp.portion_description <> 'Quantity not specified'
      and fp.gram_weight is not null
      and fp.gram_weight > 0
      and fp.portion_description !~* '\mNFS\M|\mNS as to\M|\myields\M|^Guideline amount'
    order by fp.food_id, fp.seq_num nulls last, fp.id;
$$;

revoke execute on function portion_labels_by_food_ids(bigint[], text) from public;
grant execute on function portion_labels_by_food_ids(bigint[], text)
    to anon, authenticated;
revoke execute on function portions_by_food_ids(bigint[], text) from public;
grant execute on function portions_by_food_ids(bigint[], text)
    to anon, authenticated;

-- ---------- 8. Storage --------------------------------------
-- Public bucket for food photos (thumbnail_url/main_image_url above
-- assume this bucket; prefix with your project URL in the app).
insert into storage.buckets (id, name, public)
values ('food-images', 'food-images', true)
on conflict (id) do nothing;
