-- ============================================================
-- Multi-source food schema for Supabase
-- Matches multisource_food_schema.mermaid:
--   FDC (Foundation, SR Legacy, FNDDS Survey) + BLS 4.0 + INDB,
--   images, aliases, tags, i18n.
-- Run with: supabase db push / psql "$SUPABASE_DB_URL" -f schema.sql
--
-- Load order for the generated CSVs (fdc_to_ont_csv.py,
-- bls_to_ont_csv.py, indb_to_ont_csv.py):
--   food_source, nutrient, nutrient_mapping, food_category, food,
--   food_nutrient, measure_unit, food_portion, market_acquisition,
--   input_food, food_component, retention_factor, food_image,
--   food_alias
-- then: REFRESH MATERIALIZED VIEW food_summary;
-- ============================================================

-- ---------- 1. Source registry ------------------------------

create table food_source (
    code          text primary key,          -- fdc_foundation | fdc_sr_legacy | bls
    name          text not null,
    license_note  text
);

-- ---------- 2. Canonical core -------------------------------

create table food_category (
    id           int  primary key,
    source       text references food_source (code),  -- null = canonical
    description  text not null
);

create table food (
    id                bigint primary key,
    source            text   not null references food_source (code),
    source_code       text   not null,               -- fdc_id | BLS code
    description       text   not null,               -- full English name
    short_title       text,                          -- concise display name
    food_category_id  int    references food_category (id),
    publication_date  date,
    unique (source, source_code)
);

create table nutrient (
    id         int     primary key,   -- canonical app nutrient list
    name       text    not null,
    unit_name  text    not null,      -- G | MG | UG | KCAL
    rank       numeric
);

-- Import-time mapping: source component code -> canonical nutrient.
-- `source` is the import FAMILY (fdc | bls | indb), NOT a
-- food_source.code: 'fdc' covers fdc_foundation / fdc_sr_legacy /
-- fdc_survey, so there is deliberately no FK here.
-- No FK on source_component_code either: it references FDC nutrient
-- ids, BLS component codes, INDB column names depending on source.
create table nutrient_mapping (
    source                 text    not null,
    source_component_code  text    not null,
    nutrient_id            int     not null references nutrient (id),
    unit_factor            numeric not null default 1,
    primary key (source, source_component_code)
);

create table food_nutrient (
    id           bigint  primary key,
    food_id      bigint  not null references food (id) on delete cascade,
    nutrient_id  int     not null references nutrient (id),
    amount       numeric not null,    -- per 100 g, canonical unit
    origin       text,                -- analysis | calculated | label | literature
    reference    text,
    data_points  int,
    min          numeric,
    max          numeric,
    unique (food_id, nutrient_id)
);

create table measure_unit (
    id    int  primary key,
    name  text not null
);

create table food_portion (
    id                   bigint  primary key,
    food_id              bigint  not null references food (id) on delete cascade,
    amount               numeric,
    measure_unit_id      int     not null references measure_unit (id),
    portion_description  text,
    modifier             text,
    seq_num              int,
    gram_weight          numeric not null
);

create table food_image (
    id            bigint generated by default as identity primary key,
    food_id       bigint not null references food (id) on delete cascade,
    kind          text   not null check (kind in ('thumbnail', 'main')),
    storage_path  text,               -- key in the 'food-images' bucket
    external_url  text,
    width         int,
    height        int,
    attribution   text,
    -- true when the image was AI-generated (DALL-E, Imagen...). Keep
    -- accurate: generated food photos can mislead users about what a
    -- product looks like, and disclosure rules may require labeling.
    ai_generated  boolean not null default false,
    created_at    timestamptz not null default now(),
    check (num_nonnulls(storage_path, external_url) = 1)
);

-- ---------- 2b. Search: aliases & tags ------------------------

create table food_alias (
    id          bigint generated by default as identity primary key,
    food_id     bigint not null references food (id) on delete cascade,
    locale      text   not null,     -- BCP 47: de, hi-Latn...
    alias       text   not null,     -- Spaghetti, Garam Chai...
    source      text   not null default 'curated'
                check (source in ('curated', 'community', 'derived')),
    created_at  timestamptz not null default now(),
    unique (food_id, locale, alias)
);

create table tag (
    id    int generated by default as identity primary key,
    slug  text not null unique,      -- vegan, breakfast, high-protein...
    kind  text                       -- diet | allergen | meal_type | custom
);

create table food_tag (
    food_id  bigint not null references food (id) on delete cascade,
    tag_id   int    not null references tag (id) on delete cascade,
    source   text,                   -- curated | derived | community
    primary key (food_id, tag_id)
);

create table tag_translation (
    tag_id  int  not null references tag (id) on delete cascade,
    locale  text not null,
    name    text not null,           -- vegan -> Vegan, high-protein -> Proteinreich
    primary key (tag_id, locale)
);

-- ---------- 3. Localization ---------------------------------

create table food_translation (
    food_id       bigint not null references food (id) on delete cascade,
    locale        text   not null,    -- BCP 47: de, fr, es...
    description   text   not null,
    source        text   not null default 'machine'
                  check (source in ('native', 'machine', 'community', 'verified')),
    -- true when produced by MT/LLM (DeepL, GPT...). Stays true after a
    -- human review upgrades source to 'verified', preserving provenance;
    -- may also matter for EU AI Act style disclosure duties.
    ai_generated  boolean not null default false,
    updated_at    timestamptz not null default now(),
    primary key (food_id, locale)
);

create table food_category_translation (
    food_category_id  int  not null references food_category (id) on delete cascade,
    locale            text not null,
    description       text not null,
    primary key (food_category_id, locale)
);

create table food_portion_translation (
    food_portion_id  bigint not null references food_portion (id) on delete cascade,
    locale           text   not null,
    portion_description  text,
    modifier             text,
    primary key (food_portion_id, locale)
);

create table measure_unit_translation (
    measure_unit_id  int  not null references measure_unit (id) on delete cascade,
    locale           text not null,
    name             text not null,
    primary key (measure_unit_id, locale)
);

-- ---------- 4. Source-specific side tables ------------------

create table bls_component (
    code             text primary key,   -- ENERCC, WATER, PROT625...
    name_de          text not null,
    name_en          text not null,
    unit             text not null,
    component_group  text,
    formula          text
);

create table market_acquisition (
    food_id            bigint primary key references food (id) on delete cascade,
    upc_code           text,
    brand_description  text
);

create table input_food (
    id             bigint  primary key,
    food_id        bigint  not null references food (id) on delete cascade,
    input_food_id  bigint  references food (id),
    gram_weight    numeric
);

create table food_component (
    id          bigint  primary key,
    food_id     bigint  not null references food (id) on delete cascade,
    name        text    not null,
    pct_weight  numeric,
    is_refuse   boolean not null
);

create table retention_factor (
    id           int  primary key,
    code         text not null,
    description  text not null
);

-- ---------- 5. Indexes --------------------------------------

create index idx_food_nutrient_food     on food_nutrient (food_id);
create index idx_food_portion_food      on food_portion (food_id, seq_num);
create index idx_food_image_food        on food_image (food_id, kind);
create index idx_food_translation_loc   on food_translation (locale);
create index idx_food_category_food     on food (food_category_id);

-- Full-text search: English on food, per-locale on translations.
create index idx_food_description_fts
    on food using gin (to_tsvector('english', description));
create index idx_food_translation_fts
    on food_translation using gin (to_tsvector('simple', description));
-- Fuzzy search (ILIKE '%term%') support:
create extension if not exists pg_trgm;
create index idx_food_description_trgm
    on food using gin (description gin_trgm_ops);
create index idx_food_translation_trgm
    on food_translation using gin (description gin_trgm_ops);
create index idx_food_alias_trgm
    on food_alias using gin (alias gin_trgm_ops);
create index idx_food_alias_locale on food_alias (locale, alias);
create index idx_food_tag_tag on food_tag (tag_id);

-- ---------- 6. App-facing materialized view -----------------
-- The Flutter app queries ONLY this view (+ food_translation for i18n).
-- Nutrient pivot follows MealNutrimentsDBO; canonical nutrient ids are
-- fixed by fdc_to_ont_csv.py (1=energy ... 24=niacin).

create materialized view food_summary as
select
    f.id                                   as food_id,
    f.source,
    f.source_code,
    f.description                          as name,
    coalesce(f.short_title, f.description) as short_title,  -- concise label
    ma.brand_description                   as brands,      -- MealDBO.brands
    ma.upc_code                            as barcode,     -- scanned lookup
    fc.description                         as category,
    p.amount                               as serving_quantity,
    mu.name                                as serving_unit,
    p.portion_description                  as serving_size,
    p.gram_weight                          as serving_gram_weight,
    coalesce(it.external_url, '/storage/v1/object/public/food-images/' || it.storage_path)
                                           as thumbnail_url,
    coalesce(im.external_url, '/storage/v1/object/public/food-images/' || im.storage_path)
                                           as main_image_url,
    tg.tags,
    n.energy_kcal_100,
    n.carbohydrates_100,
    n.fat_100,
    n.proteins_100,
    n.sugars_100,
    n.saturated_fat_100,
    n.fiber_100,
    n.monounsaturated_fat_100,
    n.polyunsaturated_fat_100,
    n.trans_fat_100,
    n.cholesterol_100,
    n.sodium_100,
    n.potassium_100,
    n.magnesium_100,
    n.calcium_100,
    n.iron_100,
    n.zinc_100,
    n.phosphorus_100,
    n.vitamin_a_100,
    n.vitamin_c_100,
    n.vitamin_d_100,
    n.vitamin_b6_100,
    n.vitamin_b12_100,
    n.niacin_100
from food f
left join food_category fc on fc.id = f.food_category_id
left join market_acquisition ma on ma.food_id = f.id   -- brand + barcode
left join lateral (                      -- first portion = default serving
    select fp.amount, fp.portion_description, fp.gram_weight, fp.measure_unit_id
    from food_portion fp
    where fp.food_id = f.id
    order by fp.seq_num nulls last, fp.id
    limit 1
) p on true
left join measure_unit mu on mu.id = p.measure_unit_id
left join lateral (
    select fi.external_url, fi.storage_path from food_image fi
    where fi.food_id = f.id and fi.kind = 'thumbnail'
    order by fi.id limit 1
) it on true
left join lateral (
    select fi.external_url, fi.storage_path from food_image fi
    where fi.food_id = f.id and fi.kind = 'main'
    order by fi.id limit 1
) im on true
left join lateral (
    select array_agg(t.slug order by t.slug) as tags
    from food_tag ft2
    join tag t on t.id = ft2.tag_id
    where ft2.food_id = f.id
) tg on true
left join lateral (
    select
        max(fn.amount) filter (where fn.nutrient_id = 1)  as energy_kcal_100,
        max(fn.amount) filter (where fn.nutrient_id = 2)  as carbohydrates_100,
        max(fn.amount) filter (where fn.nutrient_id = 3)  as fat_100,
        max(fn.amount) filter (where fn.nutrient_id = 4)  as proteins_100,
        max(fn.amount) filter (where fn.nutrient_id = 5)  as sugars_100,
        max(fn.amount) filter (where fn.nutrient_id = 6)  as saturated_fat_100,
        max(fn.amount) filter (where fn.nutrient_id = 7)  as fiber_100,
        max(fn.amount) filter (where fn.nutrient_id = 8)  as monounsaturated_fat_100,
        max(fn.amount) filter (where fn.nutrient_id = 9)  as polyunsaturated_fat_100,
        max(fn.amount) filter (where fn.nutrient_id = 10) as trans_fat_100,
        max(fn.amount) filter (where fn.nutrient_id = 11) as cholesterol_100,
        max(fn.amount) filter (where fn.nutrient_id = 12) as sodium_100,
        max(fn.amount) filter (where fn.nutrient_id = 13) as potassium_100,
        max(fn.amount) filter (where fn.nutrient_id = 14) as magnesium_100,
        max(fn.amount) filter (where fn.nutrient_id = 15) as calcium_100,
        max(fn.amount) filter (where fn.nutrient_id = 16) as iron_100,
        max(fn.amount) filter (where fn.nutrient_id = 17) as zinc_100,
        max(fn.amount) filter (where fn.nutrient_id = 18) as phosphorus_100,
        max(fn.amount) filter (where fn.nutrient_id = 19) as vitamin_a_100,
        max(fn.amount) filter (where fn.nutrient_id = 20) as vitamin_c_100,
        max(fn.amount) filter (where fn.nutrient_id = 21) as vitamin_d_100,
        max(fn.amount) filter (where fn.nutrient_id = 22) as vitamin_b6_100,
        max(fn.amount) filter (where fn.nutrient_id = 23) as vitamin_b12_100,
        max(fn.amount) filter (where fn.nutrient_id = 24) as niacin_100
    from food_nutrient fn
    where fn.food_id = f.id
) n on true;

-- Required for REFRESH MATERIALIZED VIEW CONCURRENTLY:
create unique index idx_food_summary_id on food_summary (food_id);
create index idx_food_summary_source on food_summary (source);
create index idx_food_summary_name_trgm
    on food_summary using gin (name gin_trgm_ops);
create index idx_food_summary_tags
    on food_summary using gin (tags);   -- WHERE tags @> array['vegan']
create index idx_food_summary_barcode   -- barcode scan lookup (branded/OFF)
    on food_summary (barcode) where barcode is not null;

-- ---------- 7. Row Level Security ---------------------------
-- Reference data: readable by everyone, writable only by service_role
-- (service_role bypasses RLS; no insert/update policies needed).

do $$
declare t text;
begin
    foreach t in array array[
        'food_source', 'food_category', 'food', 'nutrient',
        'nutrient_mapping', 'food_nutrient', 'measure_unit',
        'food_portion', 'food_image', 'food_translation',
        'food_category_translation', 'food_portion_translation',
        'measure_unit_translation', 'bls_component',
        'market_acquisition', 'input_food', 'food_component',
        'retention_factor', 'food_alias', 'tag', 'food_tag',
        'tag_translation'
    ] loop
        execute format('alter table %I enable row level security', t);
        execute format(
            'create policy "public read" on %I for select to anon, authenticated using (true)', t);
    end loop;
end $$;

-- Materialized views have no RLS; restrict via grants instead.
revoke all on food_summary from anon, authenticated;
grant select on food_summary to anon, authenticated;

-- ---------- 8. Storage --------------------------------------
-- Public bucket for food photos (thumbnail_url/main_image_url above
-- assume this bucket; prefix with your project URL in the app).
insert into storage.buckets (id, name, public)
values ('food-images', 'food-images', true)
on conflict (id) do nothing;
